### ISSUE TITLE
Increase dropdown default min-width

### ISSUE THREAD

**Issue by ajb** [dobtco/dvl-core#11]
![img](http://take.ms/bnDe5)

Shouldn't this dropdown extend to take up more width? Or should the developer explicitly set a `width` in CSS if they want a dropdown that's wider than the current `140px`?

**Comment by jrubenoff** [comment]
Yeah, I think we just need to set the `width` manually if we want to have dropdowns containing options where the text wraps.  Otherwise, the `min-width` just behaves like a `width` property.

**Comment by ajb** [comment]
K, sounds alright. Can we increase it a bit? `140px` is small, if that's what it currently is.

**Comment by jrubenoff** [comment]
Sure... it's `160` now, how about `220`?

**Comment by ajb** [comment]
Sounds good.

On Wed, Jan 7, 2015 at 1:18 PM, Josh Rubenoff <notifications@github.com>
wrote:

> Sure... it's 160 now, how about 220?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dobtco/dvl-core/issues/11#issuecomment-69093764>.
>



-- 
Adam Becker
510.928.9111
@AdamJacobBecker
