### ISSUE TITLE
Fix .form_error margin

### ISSUE THREAD

**Issue by jrubenoff** [dobtco/dvl-core#117]
![img](http://take.ms/EqMZ2)

**Comment by jrubenoff** [comment]
Also, within modals, adjacent to character counters:

![screen shot 2015-07-11 at 10 58 00 am](https://cloud.githubusercontent.com/assets/1328849/8634787/b6befe1c-27bb-11e5-9357-262e3dc7bae8.png)

**Comment by ajb** [comment]
i mean, im pretty sure this is a global issue with the component.

On Saturday, July 11, 2015, Josh Rubenoff <notifications@github.com> wrote:

> Also, within modals, adjacent to character counters:
>
> [image: screen shot 2015-07-11 at 10 58 00 am]
> <https://cloud.githubusercontent.com/assets/1328849/8634787/b6befe1c-27bb-11e5-9357-262e3dc7bae8.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dobtco/dvl-core/issues/117#issuecomment-120648313>.
>


-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker
