### ISSUE TITLE
Labels in tables

### ISSUE THREAD

**Issue by ajb** [dobtco/dvl-core#119]
![img](http://take.ms/8yLh4)

`white-space: nowrap;` seems to fix; not sure if it's a great solution.

**Comment by jrubenoff** [comment]
Since labels can be user-defined, I see this as a feature.

I would change the copy here from `Submissions closed` to `Closed` to make it look a little nicer.

**Comment by ajb** [comment]
OK, will deal with this inside of Screendoor.
