### ISSUE TITLE
global styles for figcaption

### ISSUE THREAD

**Issue by ajb** [dobtco/dvl-core#130]
It looks like `figcaption` has some global styles that might be conflicting with our components:

![img](http://dobt-captured.s3.amazonaws.com/ajb/Unsubmitted_responses_-_Screendoor_2015-07-15_16-22-58.png)

**Comment by jrubenoff** [comment]
Ahhh, I saw this when QA'ing dvl-core, and then forgot about it. Gotta look over `.progress_step_vert` in general.

Maybe we should treat figures like lists: make them unstyled by default, and require us to add a mixin for formatting when we're working with prose content.

**Comment by ajb** [comment]
> Maybe we should treat figures like lists: make them unstyled by default, and require us to add a mixin for formatting when we're working with prose content.

:+1:

**Comment by ajb** [comment]
Closed in https://github.com/dobtco/dvl-core/commit/608adb6fd9b4387c5db89cfc39a8a646927bff1e
