### ISSUE TITLE
Dark button text can look pretty bad in context

### ISSUE THREAD

**Issue by ajb** [dobtco/dvl-core#135]
![img](http://take.ms/wgyvb)

and https://github.com/dobtco/screendoor-v2/commit/c135c3385297ceb66d71c368768cd2febac61672

![img](http://dobt-captured.s3.amazonaws.com/ajb/Pingdom_project_-_Screendoor_2015-07-20_10-15-41.png)

Not sure if I have any great ideas, but I think this looks pretty darn crappy.

**Comment by jrubenoff** [comment]
- Look at Bourbon's button mixin
- Let's try making every color light and / or dark
