### ISSUE TITLE
long project names overflow on individual response pages

### ISSUE THREAD

**Issue by ajb** [dobtco/dvl-core#136]
![img](https://camo.githubusercontent.com/fe967a202b78a4898c946a1af855549dccc429fa/687474703a2f2f74616b652e6d732f674e47394f)

cf https://github.com/dobtco/screendoor-v2/issues/2269

**Comment by ajb** [comment]
I tried solving with `float: right`, but it resulted in a modified behavior when using `.page_header_secondary` http://take.ms/0xJtz, as well as a pretty undesirable layout when there was long text in the `h2`: http://take.ms/XZcO8.

**Comment by jrubenoff** [comment]
Fixed in #161
