### ISSUE TITLE
Notifications dropdown weirdness

### ISSUE THREAD

**Issue by ajb** [dobtco/dvl-core#146]
![img](http://take.ms/W8rPe)

**Comment by jrubenoff** [comment]
It appears that in this instance, "response on Sales poaching" is outside of `.drop_detail_multiline`.

Here's another example:

![screen shot 2015-08-11 at 3 31 35 pm](https://cloud.githubusercontent.com/assets/1328849/9212500/307ff61c-403e-11e5-8e5a-b143a0a478ab.png)

**Comment by ajb** [comment]
ah good catch. ill investigate

On Tuesday, August 11, 2015, Josh Rubenoff <notifications@github.com> wrote:

> It appears that in this instance, "response on Sales poaching" is outside
> of .drop_detail_multiline.
>
> Here's another example:
>
> [image: screen shot 2015-08-11 at 3 31 35 pm]
> <https://cloud.githubusercontent.com/assets/1328849/9212500/307ff61c-403e-11e5-8e5a-b143a0a478ab.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dobtco/dvl-core/issues/146#issuecomment-130098467>.
>


-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by ajb** [comment]
Closed in https://github.com/dobtco/screendoor-v2/commit/1f1811a3e7cedd9e6b24fb3293235d70f8323485
