### ISSUE TITLE
Blank options in dropdowns shouldn't display as blank

### ISSUE THREAD

**Issue by jrubenoff** [dobtco/dvl-core#153]
Blank options currently appear like this:

![screen shot 2015-08-18 at 4 10 35 pm](https://cloud.githubusercontent.com/assets/1328849/9345250/d8deda5a-45c3-11e5-8581-5f10779b8fa0.png)

We should add placeholder text:

![screen shot 2015-08-18 at 4 11 40 pm](https://cloud.githubusercontent.com/assets/1328849/9345254/e914af26-45c3-11e5-872c-e6791539e25e.png)

**Comment by ajb** [comment]
This is just a matter of markup. You could change `include_blank: true` to `include_blank: "None selected"`: https://github.com/dobtco/dvl-core/blob/3ead2744bbeccf7713279defb9ffe808ddcef218/spec/dummy/app/views/home/forms.rb#L58

**Comment by jrubenoff** [comment]
The placeholder text for the dropdown ("Choose an option") should be different than the blank value ("None selected"). Also, I'd like to add a class to the blank option if possible, so I can make the text lighter. `include_blank` values don't offer that.

**Comment by ajb** [comment]
Gotcha. I didn't realize that we were talking about rich-text droptowns. Marking as `ready` :D
