### ISSUE TITLE
Revisit page header "back button" component

### ISSUE THREAD

**Issue by ajb** [dobtco/dvl-core#162]
It doesn't work in Screendoor: https://github.com/dobtco/screendoor-v2/pull/2243

Which leads me to believe that we might need to rework the component a bit.

**Comment by jrubenoff** [comment]
From that aforementioned issue:

> The major [problem] is that if we remove the project name from the header, then a user has no way to tell which project they're currently inside of.

We can solve this with some lightweight breadcrumbs, like on forms.fm.

You also mentioned weird redundancies, like:

![](https://camo.githubusercontent.com/85359e971a1b001d5ea7b920b5b63ed2d483eb9f/687474703a2f2f74616b652e6d732f3244316276)

These seem pretty easily solvable to me:

![screen shot 2015-09-25 at 12 14 29 pm](https://cloud.githubusercontent.com/assets/1328849/10109942/10af9a2c-637f-11e5-947f-4fefc8e34935.png)

@ajb, we definitely need to think through Screendoor's info hierarchy before implementing this, but: are there any other problems you can think of with the component itself?

**Comment by ajb** [comment]
:+1:
