### ISSUE TITLE
Add the hero banner to the styleguide

### ISSUE THREAD

**Issue by ajb** [dobtco/dvl-core#179]
This is a big red flag for me: https://github.com/dobtco/dvl-core/blob/c2e697714437dc54443646d375f57f0ea5ed8fe1/spec/dummy/app/assets/stylesheets/preview.scss#L3-L40

Let's either add `hero` to the style guide, or use a `.navbar` component for this app.

**Comment by jrubenoff** [comment]
Let's do the former

**Comment by ajb** [comment]
:+1:. I think we just want the pattern from the blog?

Also, I never mentioned this, but I think there's some vertical alignment fixes that we can do when we implement:

![img](http://take.ms/jOx4d)
