### ISSUE TITLE
Selectize "multiple" styles

### ISSUE THREAD

**Issue by ajb** [dobtco/dvl-core#184]
We currently have styles for the basic "single" selectize, but we need them for the multiple too:

<img width="584" alt="screen shot 2015-10-10 at 5 23 18 pm" src="https://cloud.githubusercontent.com/assets/1270317/10413343/9fe59d0e-6f73-11e5-83f7-e832b15c8ae8.png">

**Comment by jrubenoff** [comment]
I can work on this if you open a PR.

**Comment by ajb** [comment]
https://github.com/dobtco/dvl-core/pull/185
