### ISSUE TITLE
Input text wraps inside of text input (Safari only)

### ISSUE THREAD

**Issue by ajb** [dobtco/dvl-core#187]
Very strange:

![img](http://take.ms/82Cil)

**Comment by jrubenoff** [comment]
Can't reproduce in Safari 9.0.2:

![screen shot 2016-01-04 at 5 51 33 pm](https://cloud.githubusercontent.com/assets/1328849/12105674/d042ec3c-b30b-11e5-9e2f-b433fb108a95.png)

**Comment by ajb** [comment]
Thanks for checking on this -- I just realized that I fixed it in https://github.com/dobtco/dvl-core/commit/279bd4e16b858459f15c15048d33c8ffe6823cc5.
