### ISSUE TITLE
Add 404 page to the styleguide

### ISSUE THREAD

**Issue by jrubenoff** [dobtco/dvl-core#220]
Currently:

![screen shot 2016-01-04 at 3 49 04 pm](https://cloud.githubusercontent.com/assets/1328849/12103835/b6bd9bc4-b2fa-11e5-87ef-4b1eb247a7f8.png)

**Comment by ajb** [comment]
As in, we should have a shared 404 page that we can reuse across apps? Or you're just expecting to see something prettier here?

**Comment by jrubenoff** [comment]
The latter
