### ISSUE TITLE
Find a new "primary" button color that works with light text

### ISSUE THREAD

**Issue by ajb** [dobtco/dvl-core#257]
Still think this looks kinda weird:

![img](http://take.ms/AgBAV)

**Comment by jrubenoff** [comment]
How about this? (#5E708A)

<img width="236" alt="screen shot 2016-04-20 at 4 36 21 pm" src="https://cloud.githubusercontent.com/assets/1328849/14693685/0bf06fc6-0716-11e6-8fb4-8e0e17931cf6.png">

**Comment by ajb** [comment]
Yeah, I've always been confused about the `info` vs `primary` buttons anyway. (I can take responsibility for creating this confusion, too!) And currently, our `primary` button does not match our "primary" color: http://take.ms/93hWr

So while we're on the subject, I'm all for making our button patterns easier to understand for developers. What's the point again of having `info` and `primary` buttons? Just to provide some variety?

And I like your mockup, although the font weights seem different, which is weird. Is there some smoothing going on?

**Comment by jrubenoff** [comment]
The `$primaryColor` should differ across applications... it changes according to the app's brand color.

It's probably best to rename to `primary` and `secondary`.

**Comment by ajb** [comment]
> It's probably best to rename the buttons to primary and secondary.

:+1:. If you want to PR something that looks like your mockup, I think that would be major improvement!
