### ISSUE TITLE
Smaller font size in popover confirmations

### ISSUE THREAD

**Issue by ajb** [dobtco/dvl-core#261]
It's a little chunky.

**Comment by jrubenoff** [comment]
If you just change it to `$fontSmall` I'm good with it.

**Comment by ajb** [comment]
Sure. Wasn't necessarily asking you to do this; just opening an issue as a
reminder for myself.

On Mon, May 2, 2016 at 1:56 PM, Josh Rubenoff <notifications@github.com>
wrote:

> If you just change it to $fontSmall I'm good with it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/dobtco/dvl-core/issues/261#issuecomment-216360726>
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker
