### ISSUE TITLE
Remove tooltips from navigation bar

### ISSUE THREAD

**Issue by jrubenoff** [dobtco/dvl-core#270]
I was experimenting and came up with a nicer way of displaying text labels in the navigation bar on larger screens:

![banner_interaction](https://cloud.githubusercontent.com/assets/1328849/15730359/d6d8e472-2820-11e6-9af8-e79d8ed0c1b0.gif)

**Comment by ajb** [comment]
What about long strings?

On Wed, Jun 1, 2016 at 5:47 PM, Josh Rubenoff <notifications@github.com>
wrote:

> I was experimenting and came up with a nicer way of displaying text labels
> in the navigation bar on larger screens:
>
> [image: banner_interaction]
> <https://cloud.githubusercontent.com/assets/1328849/15730359/d6d8e472-2820-11e6-9af8-e79d8ed0c1b0.gif>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dobtco/dvl-core/issues/270>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABNiLRq6lCrig-z_oAxRnjWjdzFSqjYSks5qHigZgaJpZM4IsHBu>
> .
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker
