### ISSUE TITLE
Remove dotted focus state

### ISSUE THREAD

**Issue by ajb** [dobtco/dvl-core#50]
Did we actually design this? I think it might be a relic of cardinal (the CSS framework). It's ugly and distracting IMO.

http://take.ms/xZBof

**Comment by jrubenoff** [comment]
Yeah, I have that in dobtco/screendoor-v2#1089. Ideally we'd have consistent focus states for links, buttons, etc. that were nicer than a ring and more consistent with our hover / active states. Your PR looks good for now, though.
