### ISSUE TITLE
Redesign / standardize component library

### ISSUE THREAD

**Issue by jrubenoff** [dobtco/dvl-core#54]

**Comment by jrubenoff** [comment]
https://redpen.io/p/pfe9a6dcd0fcddf8ca

Spent a few hours on this today. I'll keep chipping away at it on the side...

**Comment by ajb** [comment]
I really like this direction. I figure we can incrementally move all of our
components over to this visual style like we've already been doing a little
bit?

On Wed, Mar 11, 2015 at 8:55 PM, Josh Rubenoff <notifications@github.com>
wrote:

> https://redpen.io/p/pfe9a6dcd0fcddf8ca
>
> Spent a few hours on this today. I'll keep chipping away at it on the
> side...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dobtco/dvl-core/issues/54#issuecomment-78405006>.
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by jrubenoff** [comment]
Might make sense to try converting other apps (Opener, knowledge base, the blog) to this style before Screendoor. Low-risk way of finding out what we're missing.

**Comment by jkgoldst** [comment]
big improvement!

On Wed, Mar 11, 2015 at 6:21 PM, Josh Rubenoff <notifications@github.com>
wrote:

> Might make sense to try converting other apps (Opener, knowledge base, the
> blog) to this style before Screendoor. Low-risk way of finding out what
> we're missing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dobtco/dvl-core/issues/54#issuecomment-78407338>.
>



-- 
Josh Goldstein
CEO, Department of Better Technology (dobt.co)

**Comment by ajb** [comment]
> Might make sense to try converting other apps (Opener, knowledge base, the blog) to this style before Screendoor. Low-risk way of finding out what we're missing.

Not sure I follow, what I'm advocating for is more of what I just did for the navbar, which doesn't seem like it carries many (if any) risks.

**Comment by jrubenoff** [comment]
Sure. We need to be mindful of the order in which we tackle it, I think. Just changing core styles, or changing a component while leaving everything around it untouched, might look weird by itself. 

Did some more last night: https://redpen.io/p/pfe9a6dcd0fcddf8ca

To-do list to give you an idea of scope:

![screen shot 2015-03-12 at 11 56 58 am](https://cloud.githubusercontent.com/assets/1328849/6625705/e8358ed2-c8ae-11e4-91fa-24c3e46df0ae.png)
