### ISSUE TITLE
Focus states look weird after nav links are clicked

### ISSUE THREAD

**Issue by ajb** [dobtco/dvl-core#80]
screencast: http://dobt-captured.s3.amazonaws.com/ajb/screencast_2015-04-20_15-44-47_0_edited.mp4

I'm not sure how big of an issue this is, but I wanted to flag it since I originally thought it was a glitch of some sort.

It looks like due to our new styling of the `:focus` states in the navbar, it looks like the `hover` state is persisting after the nav links are clicked. Does that make any sense?

**Comment by jrubenoff** [comment]
Honestly I view this as a feature... you're getting extra confirmation that you clicked the link and the page is loading.

**Comment by ajb** [comment]
:+1: just checking. Thanks!
