### ISSUE TITLE
Auto-expanding textareas

### ISSUE THREAD

**Issue by jrubenoff** [dobtco/dvl-core#95]
## Problem

I see things like this pretty frequently:

![screen shot 2015-05-21 at 5 05 59 pm](https://cloud.githubusercontent.com/assets/1328849/7761518/abf319bc-ffdb-11e4-9023-5fe4226560aa.png)

![screen shot 2015-05-21 at 5 06 16 pm](https://cloud.githubusercontent.com/assets/1328849/7761561/feff635e-ffdb-11e4-95c1-71d762c5b3aa.png)

Pretty cramped.

## Proposal

Textareas that automatically expand as you add more text.

I've only seen this implemented in super-hacky ways (like a duplicate textarea positioned -1000px offscreen). @dobtco/dev, any alternatives you've seen?

**Comment by ajb** [comment]
Self-assigning because I was just researching this for formrenderer. Should be able to implement something pretty easily, I think.
